// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBlISlC3hS8w8Ad5GgeW15aI2bA6Okxg',
    appId: '1:80882013467:web:daf2dbdac587b49696afbe',
    messagingSenderId: '80882013467',
    projectId: 'taptrend-1707a',
    authDomain: 'taptrend-1707a.firebaseapp.com',
    storageBucket: 'taptrend-1707a.appspot.com',
    measurementId: 'G-2V9DLPZNLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtP3l1UhSkGjYIGZiS7xw5Hh_RpSGLwjQ',
    appId: '1:80882013467:android:3b9981ecb1c849e596afbe',
    messagingSenderId: '80882013467',
    projectId: 'taptrend-1707a',
    storageBucket: 'taptrend-1707a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZKJ7WaCoy2wk7Mlhvtf_rPbdfruXDQxI',
    appId: '1:80882013467:ios:0f3d35d7d8e531f896afbe',
    messagingSenderId: '80882013467',
    projectId: 'taptrend-1707a',
    storageBucket: 'taptrend-1707a.appspot.com',
    iosClientId: '80882013467-nic101fqp90feu6a9lvrh5gqmpaauarn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taptrend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZKJ7WaCoy2wk7Mlhvtf_rPbdfruXDQxI',
    appId: '1:80882013467:ios:63e577bb6bc27ed496afbe',
    messagingSenderId: '80882013467',
    projectId: 'taptrend-1707a',
    storageBucket: 'taptrend-1707a.appspot.com',
    iosClientId: '80882013467-oft2s7k107p06kh0m2o580uvol8ivapt.apps.googleusercontent.com',
    iosBundleId: 'com.example.taptrend.RunnerTests',
  );
}
