// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiyz4Cmm55Vz246ZXi52irVdpUWK0fgsc',
    appId: '1:497328652569:web:1fa3c194099eabd1f9c588',
    messagingSenderId: '497328652569',
    projectId: 'taptrend-fa4a9',
    authDomain: 'taptrend-fa4a9.firebaseapp.com',
    storageBucket: 'taptrend-fa4a9.appspot.com',
    measurementId: 'G-23SG2YL0WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHEwNrW5RWSgV8c_TrNG1VFN9O8DUa_XM',
    appId: '1:497328652569:android:eca579d449c10298f9c588',
    messagingSenderId: '497328652569',
    projectId: 'taptrend-fa4a9',
    storageBucket: 'taptrend-fa4a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDejL5VNNGgsFstnzOkMNE9cg-Ncd2vi6o',
    appId: '1:497328652569:ios:7f7e5b5fc5e5ee92f9c588',
    messagingSenderId: '497328652569',
    projectId: 'taptrend-fa4a9',
    storageBucket: 'taptrend-fa4a9.appspot.com',
    iosBundleId: 'com.example.taptrend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDejL5VNNGgsFstnzOkMNE9cg-Ncd2vi6o',
    appId: '1:497328652569:ios:c43fb0a3f948edbcf9c588',
    messagingSenderId: '497328652569',
    projectId: 'taptrend-fa4a9',
    storageBucket: 'taptrend-fa4a9.appspot.com',
    iosBundleId: 'com.example.taptrend.RunnerTests',
  );
}
